### PR TITLE
[#156074962] implement UI designs

### PR DESCRIPTION
**Pull request by TheSteelGuy**
Introduction

This PR impliments the pivotal story of id #156074962],
**what the pull request does**

    implements the UI design,

    contains static files for admin interfaces and user interfaces for the app

**details**

    admin interface allows adminstaration(adding new book, modidfy information about books, delete book details etc
    user can create acount, login, view profile information, borrow book and return boks etc

### CODE REVIEW

**Comment by benardokothe** [comment]
good progreess keep up

**Comment by TheSteelGuy** [comment]
just merged my development to master

**Comment by ipaullly** [comment]
Good layout and neat code. but you don't have that many comments within the code. it will help with readability

**Comment by simiyu1** [comment]
Interesting how you worked the Pivotal  stories into your commits. Will have to try it out. Did you write 

`#784y8 this commit message`
or  
`[#784y8] this commit message`

**Pull request merged**
